import { Students } from "../../../../../types/types";

export const classListf2023: Students = [
  {
    id: "#101316473",
    username: "nicolasarellanorisop",
    lastName: "Arellano (Assignment 2 example)",
    firstName: "Nicolas",
    email: "NicolasArellanoRisop@cmail.carleton.ca",
  },
  {
    id: "#101316473",
    username: "andreeannlangevin",
    lastName: "Langevin",
    firstName: "Andree-Ann",
    email: "AndreeAnnLangevin@cmail.carleton.ca",
  },
  {
    id: "#101115804",
    username: "anthonypapini",
    lastName: "Papini",
    firstName: "Anthony",
    email: "AnthonyPapini@cmail.carleton.ca",
  },
  {
    id: "#101314127",
    username: "ashlynnholman",
    lastName: "Holman",
    firstName: "Ashlynn",
    email: "AshlynnHolman@cmail.carleton.ca",
  },
  {
    id: "#101213120",
    username: "albatoolhayajneh",
    lastName: "Hayajneh",
    firstName: "Batool",
    email: "ALBATOOLHAYAJNEH@cmail.carleton.ca",
  },
  {
    id: "#101316637",
    username: "bensegal",
    lastName: "Segal",
    firstName: "Ben",
    email: "BenSegal@cmail.carleton.ca",
  },
  {
    id: "#101309591",
    username: "bryannamcghee",
    lastName: "Mcghee",
    firstName: "Bryanna",
    email: "BryannaMcghee@cmail.carleton.ca",
  },
  {
    id: "#101316484",
    username: "colemarotta",
    lastName: "Marotta",
    firstName: "Cole",
    email: "ColeMarotta@cmail.carleton.ca",
  },
  {
    id: "#101304810",
    username: "daphnestams",
    lastName: "Stams",
    firstName: "Daphne",
    email: "daphnestams@cmail.carleton.ca",
  },
  {
    id: "#101143435",
    username: "dylanjozkow",
    lastName: "Jozkow",
    firstName: "Dylan",
    email: "DylanJozkow@cmail.carleton.ca",
  },
  {
    id: "#101278784",
    username: "evanmartyn",
    lastName: "Martyn",
    firstName: "Evan",
    email: "EvanMartyn@cmail.carleton.ca",
  },
  {
    id: "#101274348",
    username: "farbodeinisarghin",
    lastName: "Eini Sarghin",
    firstName: "Farbod",
    email: "FarbodEiniSarghin@cmail.carleton.ca",
  },
  {
    id: "#100963190",
    username: "farisitum",
    lastName: "Itum",
    firstName: "Faris",
    email: "farisitum@cmail.carleton.ca",
  },
  {
    id: "#101194400",
    username: "filipecosta3",
    lastName: "Costa",
    firstName: "Filipe",
    email: "FILIPECOSTA3@cmail.carleton.ca",
  },
  {
    id: "#101203897",
    username: "jeremielafleche",
    lastName: "Lafleche",
    firstName: "Jeremie",
    email: "JEREMIELAFLECHE@cmail.carleton.ca",
  },
  {
    id: "#101296441",
    username: "keeganmetheringham",
    lastName: "Metheringham",
    firstName: "Keegan",
    email: "KeeganMetheringham@cmail.carleton.ca",
  },
  {
    id: "#101108961",
    username: "lillianelkadri",
    lastName: "El-Kadri",
    firstName: "Lillian",
    email: "LillianElKadri@cmail.carleton.ca",
  },
  {
    id: "#101290705",
    username: "melaniexie",
    lastName: "Xie",
    firstName: "Melanie",
    email: "MelanieXie@cmail.carleton.ca",
  },
  {
    id: "#101120799",
    username: "mikhalagibson",
    lastName: "Gibson",
    firstName: "Mikhala",
    email: "MikhalaGibson@cmail.carleton.ca",
  },
  {
    id: "#101309208",
    username: "muchenge",
    lastName: "Ge",
    firstName: "Muchen",
    email: "MuchenGe@cmail.carleton.ca",
  },
  {
    id: "#101314173",
    username: "muqujenniferliu",
    lastName: "Liu",
    firstName: "Mu Qu Jennifer",
    email: "MuQuJenniferLiu@cmail.carleton.ca",
  },
  {
    id: "#101111524",
    username: "oskarkalm",
    lastName: "Kalm",
    firstName: "Oskar",
    email: "OskarKalm@cmail.carleton.ca",
  },
  {
    id: "#101113566",
    username: "simonmartignago",
    lastName: "Martignago",
    firstName: "Simon",
    email: "SimonMartignago@cmail.carleton.ca",
  },
  {
    id: "#101316485",
    username: "theojemtrud",
    lastName: "Jemtrud",
    firstName: "Theo",
    email: "TheoJemtrud@cmail.carleton.ca",
  },
  {
    id: "#101088385",
    username: "vanessadealexandris",
    lastName: "De Alexandris",
    firstName: "Vanessa",
    email: "VanessaDeAlexandris@cmail.carleton.ca",
  },
  {
    id: "#101276372",
    username: "vincenttourangeau",
    lastName: "Tourangeau",
    firstName: "Vincent",
    email: "VincentTourangeau@cmail.carleton.ca",
  },
  {
    id: "#101008770",
    username: "weixizhong",
    lastName: "Zhong",
    firstName: "Weixi",
    email: "weixizhong@cmail.carleton.ca",
  },
];
