import { Students } from "../../../../types/types";

export const classListf2024: Students = [
  {
    id: "#101112560",
    username: "nicolasarellanorisop",
    lastName: "Arellano (Final Assignment Example)",
    firstName: "Nicolas",
    email: "NicolasArellanoRisop@cmail.carleton.ca",
  },
  {
    id: "#101088562",
    username: "AbirMakki",
    lastName: "Makki",
    firstName: "Abir",
    email: "AbirMakki@cmail.carleton.ca",
  },
  {
    id: "#101194124",
    username: "ALEXISGAWLINA",
    lastName: "Gawlina",
    firstName: "Alexis",
    email: "ALEXISGAWLINA@cmail.carleton.ca",
  },
  {
    id: "#101352266",
    username: "AlvinAhn",
    lastName: "Ahn",
    firstName: "Alvin",
    email: "AlvinAhn@cmail.carleton.ca",
  },
  {
    id: "#101071598",
    username: "AndreCusson",
    lastName: "Cusson",
    firstName: "Andre",
    email: "AndreCusson@cmail.carleton.ca",
  },
  {
    id: "#101351193",
    username: "AshaStott",
    lastName: "Stott",
    firstName: "Asha",
    email: "AshaStott@cmail.carleton.ca",
  },
  {
    id: "#101157564",
    username: "BasilCurrie",
    lastName: "Currie",
    firstName: "Basil",
    email: "BasilCurrie@cmail.carleton.ca",
  },
  {
    id: "#101348214",
    username: "ChloeTheriault",
    lastName: "Theriault",
    firstName: "Chloe",
    email: "ChloeTheriault@cmail.carleton.ca",
  },
  {
    id: "#101352783",
    username: "ChristopherSproule",
    lastName: "Sproule",
    firstName: "Christopher",
    email: "ChristopherSproule@cmail.carleton.ca",
  },
  {
    id: "#101293693",
    username: "DennisAvgerinos",
    lastName: "Avgerinos",
    firstName: "Dennis",
    email: "DennisAvgerinos@cmail.carleton.ca",
  },
  {
    id: "#101114665",
    username: "faezaafrin",
    lastName: "Afrin",
    firstName: "Faeza",
    email: "faezaafrin@cmail.carleton.ca",
  },
  {
    id: "#101185453",
    username: "HASEENADOOST",
    lastName: "Doost",
    firstName: "Haseena",
    email: "HASEENADOOST@cmail.carleton.ca",
  },
  {
    id: "#101044786",
    username: "HassanHannawi",
    lastName: "Hannawi",
    firstName: "Hassan",
    email: "HassanHannawi@cmail.carleton.ca",
  },
  {
    id: "#101351899",
    username: "joshharriman",
    lastName: "Harriman",
    firstName: "Josh",
    email: "joshharriman@cmail.carleton.ca",
  },
  {
    id: "#101051189",
    username: "KaleighMackay",
    lastName: "Mackay",
    firstName: "Kaleigh",
    email: "KaleighMackay@cmail.carleton.ca",
  },
  {
    id: "#101348250",
    username: "KayleeKomatich",
    lastName: "Komatich",
    firstName: "Kaylee",
    email: "KayleeKomatich@cmail.carleton.ca",
  },
  {
    id: "#101180890",
    username: "MAISJOUDEH",
    lastName: "Joudeh",
    firstName: "Mais",
    email: "MAISJOUDEH@cmail.carleton.ca",
  },
  {
    id: "#101183487",
    username: "MARIAFARES",
    lastName: "Fares",
    firstName: "Maria",
    email: "MARIAFARES@cmail.carleton.ca",
  },
  {
    id: "#101348025",
    username: "MostafaBdeir",
    lastName: "Bdeir",
    firstName: "Mostafa",
    email: "MostafaBdeir@cmail.carleton.ca",
  },
  {
    id: "#101156529",
    username: "NoahEPerkins",
    lastName: "Perkins",
    firstName: "Noah",
    email: "NoahEPerkins@cmail.carleton.ca",
  },
  {
    id: "#101345562",
    username: "RashidaLeslie",
    lastName: "Leslie",
    firstName: "Rashida",
    email: "RashidaLeslie@cmail.carleton.ca",
  },
  {
    id: "#101004334",
    username: "rebeccasondermeyer",
    lastName: "Sondermeyer",
    firstName: "Rebecca",
    email: "rebeccasondermeyer@cmail.carleton.ca",
  },
  {
    id: "#101052132",
    username: "SaraniaDabee",
    lastName: "Dabee",
    firstName: "Sarania",
    email: "SaraniaDabee@cmail.carleton.ca",
  },
  {
    id: "#101348281",
    username: "SunWooPark",
    lastName: "Park",
    firstName: "Sun-Woo",
    email: "SunWooPark@cmail.carleton.ca",
  },
  {
    id: "#101041412",
    username: "TessComan",
    lastName: "Coman",
    firstName: "Tess",
    email: "TessComan@cmail.carleton.ca",
  },
  {
    id: "#101348046",
    username: "ZelalKaya",
    lastName: "Kaya",
    firstName: "Zelal",
    email: "ZelalKaya@cmail.carleton.ca",
  },
];
