import { Students } from '../../../../../types/types';

export const classListf2024: Students = [
  {
    id: '#101352266',
    username: 'alvinahn',
    lastName: 'Ahn',
    firstName: 'Alvin',
    email: 'AlvinAhn@cmail.carleton.ca',
    assignments: ['about'],
<<<<<<< HEAD
=======
  },
  {
    id: '#101071598',
    username: 'andrecusson',
    lastName: 'Cusson',
    firstName: 'Andre',
    email: 'AndreCusson@cmail.carleton.ca',
    assignments: ['about', 'three'],
  },
  {
    id: '#101351193',
    username: 'ashastott',
    lastName: 'Stott',
    firstName: 'Asha',
    email: 'AshaStott@cmail.carleton.ca',
    assignments: ['about', 'three'],
  },
  {
    id: '#101157564',
    username: 'basilcurrie',
    lastName: 'Currie',
    firstName: 'Basil',
    email: 'BasilCurrie@cmail.carleton.ca',
    assignments: ['about', 'three', 'bim'],
  },
  {
    id: '101187201',
    username: 'chloemaignan',
    lastName: 'Maignan',
    firstName: 'Chloe',
    email: 'CHLOEMAIGNAN@cmail.carleton.ca',
    assignments: ['about', 'three'],
  },
  {
    id: '#101348214',
    username: 'chloetheriault',
    lastName: 'Theriault',
    firstName: 'Chloe',
    email: 'ChloeTheriault@cmail.carleton.ca',
    assignments: ['about', 'three'],
  },
  {
    id: '#101352783',
    username: 'christophersproule',
    lastName: 'Sproule',
    firstName: 'Christopher',
    email: 'ChristopherSproule@cmail.carleton.ca',
    assignments: ['about', 'three'],
  },
  {
    id: '101078481',
    username: 'danielkendall',
    lastName: 'Kendall',
    firstName: 'Daniel',
    email: 'DanielKendall@cunet.carleton.ca',
    assignments: ['about'],
  },
  {
    id: '#101293693',
    username: 'dennisavgerinos',
    lastName: 'Avgerinos',
    firstName: 'Dennis',
    email: 'DennisAvgerinos@cmail.carleton.ca',
    assignments: ['about', 'three', 'bim'],
>>>>>>> origin/master
  },
  {
    id: '#101114665',
    username: 'faezaafrin',
    lastName: 'Afrin',
    firstName: 'Faeza',
    email: 'faezaafrin@cmail.carleton.ca',
    assignments: ['about', 'three'],
  },
  {
    id: '#101112560',
    username: 'nicolasarellanorisop',
    lastName: 'Arellano',
    firstName: 'Nicolas',
    email: 'NicolasArellanoRisop@cmail.carleton.ca',
    assignments: ['about', 'three', 'map', 'bim'],
  },
  {
<<<<<<< HEAD
    id: '#101293693',
    username: 'dennisavgerinos',
    lastName: 'Avgerinos',
    firstName: 'Dennis',
    email: 'DennisAvgerinos@cmail.carleton.ca',
    assignments: ['about', 'three', 'bim'],
=======
    id: '#101044786',
    username: 'hassanhannawi',
    lastName: 'Hannawi',
    firstName: 'Hassan',
    email: 'HassanHannawi@cmail.carleton.ca',
    assignments: ['about'],
  },
  {
    id: '#101195968',
    username: 'jasminehersh',
    lastName: 'Hersh',
    firstName: 'Jasmine',
    email: 'jasminehersh@cmail.carleton.ca',
    assignments: ['about', 'three'],
  },
  {
    id: '#101315584',
    username: 'jaspersilverking',
    lastName: 'Silver-King',
    firstName: 'Jasper',
    email: 'jaspersilverking@cmail.carleton.ca',
    assignments: ['about', 'three'],
  },
  {
    id: '#101351899',
    username: 'joshharriman',
    lastName: 'Harriman',
    firstName: 'Josh',
    email: 'joshharriman@cmail.carleton.ca',
    assignments: ['about', 'three'],
  },
  {
    id: '#101051189',
    username: 'kaleighmackay',
    lastName: 'Mackay',
    firstName: 'Kaleigh',
    email: 'KaleighMackay@cmail.carleton.ca',
    assignments: ['about', 'three'],
  },
  {
    id: '#101348250',
    username: 'kayleekomatich',
    lastName: 'Komatich',
    firstName: 'Kaylee',
    email: 'KayleeKomatich@cmail.carleton.ca',
    assignments: ['about', 'three'],
  },
  {
    id: '#101180890',
    username: 'maisjoudeh',
    lastName: 'Joudeh',
    firstName: 'Mais',
    email: 'MAISJOUDEH@cmail.carleton.ca',
    assignments: ['about', 'three'],
  },
  {
    id: '#101183487',
    username: 'mariafares',
    lastName: 'Fares',
    firstName: 'Maria',
    email: 'MARIAFARES@cmail.carleton.ca',
    assignments: ['about', 'three'],
>>>>>>> origin/master
  },
  {
    id: '#101348025',
    username: 'mostafabdeir',
    lastName: 'Bdeir',
    firstName: 'Mostafa',
    email: 'MostafaBdeir@cmail.carleton.ca',
    assignments: ['about', 'three'],
  },
  {
    id: '#101041412',
    username: 'tesscoman',
    lastName: 'Coman',
    firstName: 'Tess',
    email: 'TessComan@cmail.carleton.ca',
    assignments: ['about', 'three'],
  },
  {
    id: '#101157564',
    username: 'basilcurrie',
    lastName: 'Currie',
    firstName: 'Basil',
    email: 'BasilCurrie@cmail.carleton.ca',
    assignments: ['about', 'three', 'bim'],
  },
  {
    id: '#101071598',
    username: 'andrecusson',
    lastName: 'Cusson',
    firstName: 'Andre',
    email: 'AndreCusson@cmail.carleton.ca',
    assignments: ['about', 'three'],
  },
  {
    id: '#101052132',
    username: 'saraniadabee',
    lastName: 'Dabee',
    firstName: 'Sarania',
    email: 'SaraniaDabee@cmail.carleton.ca',
    assignments: ['about', 'three'],
  },
  {
    id: '#101185453',
    username: 'haseenadoost',
    lastName: 'Doost',
    firstName: 'Haseena',
    email: 'HASEENADOOST@cmail.carleton.ca',
    assignments: ['about', 'three'],
  },
  {
    id: '#101183487',
    username: 'mariafares',
    lastName: 'Fares',
    firstName: 'Maria',
    email: 'MARIAFARES@cmail.carleton.ca',
    assignments: ['about', 'three'],
  },
  {
    id: '#101194124',
    username: 'alexisgawlina',
    lastName: 'Gawlina',
    firstName: 'Alexis',
    email: 'ALEXISGAWLINA@cmail.carleton.ca',
    assignments: ['about', 'three'],
  },
  {
    id: '#101044786',
    username: 'hassanhannawi',
    lastName: 'Hannawi',
    firstName: 'Hassan',
    email: 'HassanHannawi@cmail.carleton.ca',
    assignments: ['about'],
  },
  {
    id: '#101351899',
    username: 'joshharriman',
    lastName: 'Harriman',
    firstName: 'Josh',
    email: 'joshharriman@cmail.carleton.ca',
    assignments: ['about', 'three'],
  },
  {
    id: '#101195968',
    username: 'jasminehersh',
    lastName: 'Hersh',
    firstName: 'Jasmine',
    email: 'jasminehersh@cmail.carleton.ca',
    assignments: ['about', 'three'],
  },
  {
    id: '#101180890',
    username: 'maisjoudeh',
    lastName: 'Joudeh',
    firstName: 'Mais',
    email: 'MAISJOUDEH@cmail.carleton.ca',
    assignments: ['about', 'three'],
  },
  {
    id: '#101348281',
    username: 'sunwoopark',
    lastName: 'Park',
    firstName: 'Sun-Woo',
    email: 'SunWooPark@cmail.carleton.ca',
    assignments: ['about', 'three'],
  },
  {
    id: '#101348250',
    username: 'kayleekomatich',
    lastName: 'Komatich',
    firstName: 'Kaylee',
    email: 'KayleeKomatich@cmail.carleton.ca',
    assignments: ['about', 'three'],
  },
  {
    id: '#101078481',
    username: 'danielkendall',
    lastName: 'Kendall',
    firstName: 'Daniel',
    email: 'DanielKendall@cunet.carleton.ca',
    assignments: ['about', 'three'],
  },
  {
    id: '#101345562',
    username: 'rashidaleslie',
    lastName: 'Leslie',
    firstName: 'Rashida',
    email: 'RashidaLeslie@cmail.carleton.ca',
    assignments: ['about', 'three'],
  },
  {
    id: '#101159867',
    username: 'williamlozides',
    lastName: 'Lozides',
    firstName: 'William',
    email: 'williamlozides@cmail.carleton.ca',
    assignments: ['about', 'three'],
  },
  {
    id: '#101051189',
    username: 'kaleighmackay',
    lastName: 'Mackay',
    firstName: 'Kaleigh',
    email: 'KaleighMackay@cmail.carleton.ca',
    assignments: ['about', 'three'],
  },
  {
    id: '101187201',
    username: 'chloemaignan',
    lastName: 'Maignan',
    firstName: 'Chloe',
    email: 'CHLOEMAIGNAN@cmail.carleton.ca',
    assignments: ['about', 'three'],
  },
  {
    id: '#101088562',
    username: 'abirmakki',
    lastName: 'Makki',
    firstName: 'Abir',
    email: 'AbirMakki@cmail.carleton.ca',
    assignments: ['about', 'three'],
  },
  {
    id: '101150519',
    username: 'shaganamuttiah',
    lastName: 'Muttiah',
    firstName: 'Shagana',
    email: 'shaganamuttiah@cmail.carleton.ca',
    assignments: ['about', 'three'],
  },
  {
    id: '#101156529',
    username: 'noaheperkins',
    lastName: 'Perkins',
    firstName: 'Noah',
    email: 'NoahEPerkins@cmail.carleton.ca',
    assignments: ['about', 'three'],
  },
  {
    id: '#101315584',
    username: 'jaspersilverking',
    lastName: 'Silver-King',
    firstName: 'Jasper',
    email: 'jaspersilverking@cmail.carleton.ca',
    assignments: ['about', 'three'],
  },
  {
    id: '#101004334',
    username: 'rebeccasondermeyer',
    lastName: 'Sondermeyer',
    firstName: 'Rebecca',
    email: 'rebeccasondermeyer@cmail.carleton.ca',
    assignments: ['about', 'three'],
  },
  {
    id: '#101352783',
    username: 'christophersproule',
    lastName: 'Sproule',
    firstName: 'Christopher',
    email: 'ChristopherSproule@cmail.carleton.ca',
    assignments: ['about', 'three'],
  },
  {
    id: '#101351193',
    username: 'ashastott',
    lastName: 'Stott',
    firstName: 'Asha',
    email: 'AshaStott@cmail.carleton.ca',
    assignments: ['about', 'three'],
  },
  {
    id: '#101348214',
    username: 'chloetheriault',
    lastName: 'Theriault',
    firstName: 'Chloe',
    email: 'ChloeTheriault@cmail.carleton.ca',
    assignments: ['about', 'three'],
  },
  {
    id: '#101348046',
    username: 'zelalkaya',
    lastName: 'Kaya',
    firstName: 'Zelal',
    email: 'ZelalKaya@cmail.carleton.ca',
    assignments: ['about', 'three'],
  },
];

// Sort the array by lastName
classListf2024.sort((a, b) => a.lastName.localeCompare(b.lastName));
